version: '3'
services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb:rw
    environment:
      - INFLUXDB_DB=weather
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    networks:
      - my_network

  telegraf:
    image: telegraf:1.19
    container_name: telegraf
    depends_on:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /root/.cache/snowflake:/root/.cache/snowflake
    environment:
      - APP_ID=${APP_ID}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_DB=weather
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    restart: always
    networks:
      - my_network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    networks:
      - my_network

volumes:
  influxdb_data: {}   # Déclaration explicite du volume
  grafana_data: {}

networks:
  my_network:
    driver: bridge
